### ISSUE TITLE
NA PA - Enhance the photo size for desktop/laptop 

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#10]
**Is your feature request related to a problem? Please describe.**
Currently the photo sizing is the screen width. It's perfect for mobile but not optimal for desktop/laptop/tablet users.
Is expected a solution allowing the photo resizing for a better usability for desktop/laptop/tablet

**Describe the solution you'd like**
Ideally a desktop/laptop/tablet detection to display a carousel with a fixed width size. With a possibility to open the photo at its real size.

**Describe alternatives you've considered**
If the desktop/laptop/tablet  detection isn't possible, perhaps using a variable like "authorizer"/"updater".
Any simple low cost solution enhancing the usability will be acceptable.

**Additional context**
NA

**Comment by be-ant** [comment]
Here is the suggested change:

For big screens the image will be at the right (with a max height set) with the possibility of clicking on it and open it in a new tab

![image](https://user-images.githubusercontent.com/91206666/209175336-4f806504-5384-4009-be69-f168516fceac.png)

For smaller screens it will be presented the same way it is right now:

![image](https://user-images.githubusercontent.com/91206666/209175477-bee1664f-4657-4dc7-a0cf-2713abb7c7e7.png)

**Comment by DelphinoVarela** [comment]
Looks great

**Comment by mm-catdev** [comment]
Delivered in 1.0.6

**Comment by DelphinoVarela** [comment]
Installed and tested okay
