### ISSUE TITLE
NA PA - Enhance the group expansion/reduction icons  

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#11]
**Is your feature request related to a problem? Please describe.**
A group with more than one item has an icon + to expand an see all items. The icon size and contrast isn't ideal

**Describe the solution you'd like**
1- a bigger icon
2- the + or - symbol with more contrast compared to the background 

**Describe alternatives you've considered**
Any solution enhancing the visibility/usability

**Additional context**
NA

**Comment by mm-catdev** [comment]
Improvement delivered in Release 1.0.5

**Comment by DelphinoVarela** [comment]
Change tested and approved
