### ISSUE TITLE
NA PA - Enhance plugin colors

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#12]
**Is your feature request related to a problem? Please describe.**
Current colors are not optimal in Naturgy context (not corporate colors..)

**Describe the solution you'd like**
- Active buttons : #004571
- Inactive buttons : #CFE4F7
- Active header (like "Listado de Formularios") : #CFE4F7
- Text in the active header : #004571

**Describe alternatives you've considered**
Any setting based on #004571 with good contrast (https://webaim.org/resources/contrastchecker/)

**Additional context**
NA

**Comment by mm-catdev** [comment]
Delivered in 1.0.6

**Comment by DelphinoVarela** [comment]
Installed and tested okay
