### ISSUE TITLE
NA PA - Impossible to load a new plugin

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#13]
**Affected Plugin**
VAL-FORM

**Describe the bug**
It's impossible to loas a new plugin

**To Reproduce**
1. Try to upload a new plugin (without any directory in the zip (no css, images or others))

**Current behavior**
An error message is displayed : "Quantity of files and folders is 16, which exceeds maximum allowed quantity (10)"

**Expected behavior**
As, excluding VAL-FORM, Naturgy Panama has only 3 plugins we shouldn't have this kind of error (only Plugin_Validacion_Usuarios is "consuming" 2 directories. If I'm enhancing it I will get the same error message).

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Hi Delphino,

Which zip are you trying to upload ? Our zip works without any problem in our environments...

Regards

**Comment by DelphinoVarela** [comment]
Your zip work correctly but "consumed" all "resources" which prevents to load a new plugin.
I'm attaching here the zip I'm tryin to upload. Optimizing it (moving the fies from 2 directories to the root then changing the manifest and the index.html) I went from the message :
"Quantity of files and folders is 20, which exceeds maximum allowed quantity (10)" 
to 
"Quantity of files and folders is 16, which exceeds maximum allowed quantity (10)"

[Plugin_Validacion_Usuario.zip](https://github.com/ST3AM-US/st3am-com-issues/files/10683214/Plugin_Validacion_Usuario.zip)

**Comment by be-ant** [comment]
We can pack it. That’s not an issue at all but as far as I know plug-ins
don’t consume “shared” number of files. A very simple proof of that: the
max number of authorized is (I think) 25. Even if each one consumed only 2
files (index + js) then the “shared” max possible  number of files should
be at least 200…

That number (10) is per plugin.  We offer to help you pack the other one
also.

**Comment by mm-catdev** [comment]
I have validated that the problem is with the zip itself.

I have reproduced my issue in my demo environment.

![image](https://user-images.githubusercontent.com/91625466/217574394-1a580e86-e882-429c-b6b3-3e37b185cc93.png)

that said, I would suggest you to use zip through command tool in order to avoid any hidden file or any folder to be included in the zip

In the source code folder, execute something like this 

 zip plugin.zip *.html *.svg *.css *.js

**Comment by DelphinoVarela** [comment]
Tested okay. Thx

**Comment by DelphinoVarela** [comment]
zip ../plugin.zip -r assets/js/*.js -r assets/js/base/*.js -r assets/js/utils/*.js -r assets/css/*.css assets/bootstrap/css/*.css *.html
