### ISSUE TITLE
NA PA - "OK" button position enhancement

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#15]
**Is your feature request related to a problem? Please describe.**
With current version the "Cancel" and "OK" buttons requires a scroll to reach them (event if the list of form isn't filling the all screen). The consequences : 
  - user forget to press "OK" and use "Activity details" to return to exit the plugin
  - PA_SIT_FORM_DATOS_0 isn't updated 

**Describe the solution you'd like**
Have the "Ok" button in a higher position (in a header ? Top left position to be closer from the "Activity details" ?). Position of "Cancel" button is less "critical".
Any solution maximizing the visibility of the "OK" button before clicking "Activity details".

**Describe alternatives you've considered**
Minimum solution have the "Cancel" and "OK" buttons in fixed position at the bottom of the screen

**Additional context**
Screenshot example of current situation (buttons are not appearing at the bottom because of the scroll)
![image](https://user-images.githubusercontent.com/65107297/221237884-a0bc3978-4007-4e24-b33e-dd23d079c0ce.png)

**Comment by mm-catdev** [comment]
Tested ok

**Comment by mm-catdev** [comment]
![image](https://user-images.githubusercontent.com/91625466/226433631-c081d1bd-4d5c-40ce-a138-0a3bd925e33f.png)

**Comment by mm-catdev** [comment]
Delivered in Release 1.0.7

**Comment by DelphinoVarela** [comment]
Tested okay
