### ISSUE TITLE
NA PA - "reason" visibility from a mobile

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#16]
How can we se the "reason" (after a "Rechazo") when we are using a mobile ? 
I'm not identifying it in portrait mode or opening the details (see screenshots). I tried various definition and the horizontal scroll.

![image](https://user-images.githubusercontent.com/65107297/223219131-5b72ca26-e8d1-4498-8e24-727571acb69e.png)
![image](https://user-images.githubusercontent.com/65107297/223219166-16de054d-220e-4b73-a6ae-6d8315e8ab89.png)

**Comment by mm-catdev** [comment]
Included steps to reproduce in https://naturgy-pa-des.test.etadirect.com/mobility/

Open work order 865204
Make the browser smaller
The reason of the rejected form is not longer visible.

**Comment by mm-catdev** [comment]
We have 3 options, which one do you think is better for the customer ? 

Hint message when the technician moves over the line.
Include the rejected reason on the title of the line details screen
Include the rejected reason on the details of the line, together with the notes and the description

**Comment by DelphinoVarela** [comment]
Preferred option : Include the rejected reason on the details of the line, together with the notes and the description

Best position : on top of the list (prior Description).

**Comment by mm-catdev** [comment]
Tested ok

![image](https://user-images.githubusercontent.com/91625466/226442932-85e90e37-8011-431e-90c4-7952c62d612a.png)

**Comment by mm-catdev** [comment]
Delivered in Release 1.0.7

**Comment by DelphinoVarela** [comment]
Rejected after test.
See the screenshoots : 
- 1st the Rejection reason is "Test 23/03/2023"
- 2nd the "Razon Rechazado" is "undefined"

During the correction, please, can you add the same space between "Razon Rechazado" content and "Descripcion" then from "Descripcion" content and "Notas" ?

![image](https://user-images.githubusercontent.com/65107297/227172300-1ec1f144-0978-40ec-9503-508679ed77fc.png)

![image](https://user-images.githubusercontent.com/65107297/227172359-fc554ec1-a2ee-4bf1-b417-7eb70279e323.png)

**Comment by DelphinoVarela** [comment]
I think I found the issue in custom.js.
- instead of 
            var details =
                plugin.form.status & REJECTED
                    ? `<p class="fw-bold text-dark">Razón Rechazo:</p>${plugin.form.reject_reason}`
                    : "";
- it should be             
            var details =
                plugin.form.status & REJECTED
                    ? `<p class="fw-bold text-dark">Razón Rechazo:</p>${plugin.form.reason}<P>`
                    : "";

reject_reason isn't existing in PA_SIT_FORM_DATOS_0

**Comment by DelphinoVarela** [comment]
Remaining challenge I'm not able to solve : 
"Razón Rechazo" is displayed no matter the status (plugin.form.status & REJECTED condition isn't working)

**Comment by mm-catdev** [comment]
Solved in V1_0_8

**Comment by DelphinoVarela** [comment]
Tested KO (same behavior than Release 1.0.7)

**Comment by mm-catdev** [comment]
Delivered in 1.0.8

**Comment by DelphinoVarela** [comment]
Tested OK
