### ISSUE TITLE
NA PA - Remove the "easter egg"

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#18]
**Affected Plugin**
VAL-FORM

**Describe the bug**
Some photos not loaded by any user are displayed

**To Reproduce**
1. Open VAL-FORM (no matter if a Report was already done or not)
2. Click on the right icon of "Listado de Formularios" to collapse the list 
![image](https://user-images.githubusercontent.com/65107297/227175227-7ca0bef9-d3ef-47aa-8fd3-c60fea3d223c.png)

3. Click on the bar "Detalles" (turning it blue)

**Current behavior**
Cats photos are displayed
![image](https://user-images.githubusercontent.com/65107297/227175118-736dd89b-99d8-451d-9fb4-cd0d40dde4e7.png)

**Expected behavior**
Nothing should be displayed

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Hi!

Can you give us an activity so we can properly test it ?

By the way , our user is no longer working, so we can't reproduce it.

**Comment by DelphinoVarela** [comment]
Hi,

It can be reproduced with any activity.
I refreshed the Dev. env. forgetting about your user.
What was the user : plugin ?
I created : "plugin" / "$sT3AM2023$"

**Comment by DelphinoVarela** [comment]
The issue is located there (in the "src" setting) : 

`<div class="carousel-item active align-content-center carousel-item-base" id="slide_0" data-ofs-order="0"><img class="img-fluid w-100 d-block" id="image_0" alt="Slide Image" src="https://via.placeholder.com/1200x904.jpg"></div>
                                    <div class="carousel-item carousel-item-base" id="slide_1" data-ofs-order="1"><img class="img-fluid w-100 d-block" id="image_1" src="https://loremflickr.com/640/1200" alt="Slide Image"></div>
                                    <div class="carousel-item carousel-item-base" id="slide_2" data-ofs-order="2"><img class="img-fluid w-100 d-block" id="image_2" src="https://loremflickr.com/1024/768"></div>
                                    <div class="carousel-item carousel-item-base" id="slide_3" data-ofs-order="3"><img class="img-fluid w-100 d-block" id="image_3" src="https://loremflickr.com/640/360" alt="Slide Image"></div>
                                    <div class="carousel-item carousel-item-base" id="slide_4" data-ofs-order="4"><img class="img-fluid w-100 d-block" id="image_4" src="https://via.placeholder.com/1400x803.jpg" alt="Slide Image"></div>`

**Comment by mm-catdev** [comment]
I have been able to reproduce it.

**Comment by mm-catdev** [comment]
Delivered in Release 1.0.8

**Comment by DelphinoVarela** [comment]
Tested KO (same behavior than Release 1.0.7)

**Comment by mm-catdev** [comment]
Delivered in 1.0.8

**Comment by DelphinoVarela** [comment]
Tested OK
