### ISSUE TITLE
NA PA - Version displayed

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#19]
**Affected Plugin**
VAL-FORM

**Describe the bug**
Plugin displays on the center bottom : {{VERSION}}

**To Reproduce**
NA

**Expected behavior**
The plugin version should be displayed (a variable defined somewhere I guess)

**Screenshots**
![image](https://user-images.githubusercontent.com/65107297/227209961-718aa5f7-f35c-4fd8-b328-37f529f81d1b.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Delivered in Release 1.0.8

**Comment by DelphinoVarela** [comment]
Tested KO (same behavior than Release 1.0.7)

**Comment by mm-catdev** [comment]
Delivered in 1.0.8

**Comment by DelphinoVarela** [comment]
Tested OK
