### ISSUE TITLE
Test XML Provided are not aligned with XSD

### ISSUE THREAD

**Issue by mm-catdev** [ST3AM-US/st3am-com-issues#21]
**Affected Plugin / Project**
DIY Activities Management

**Describe the bug**
The XML doesn't parse with the agreed XSD

**To Reproduce**
Open the XML attached and parse and parse against the XSD https://drive.google.com/file/d/1xDDbUxw-7OigmiLDKoS5-ufI_zXzadmK/view?usp=drive_link

**Expected behavior**
To parse properly

**Screenshots**
The field xs:long can´t be empty, but the example contains the tag ShipToPhone empty

**Comment by mm-catdev** [comment]
[INT001SCMS05_ShipReq_ORA_VDIYFR_69646215_20230707055117.txt](https://github.com/ST3AM-US/st3am-com-issues/files/12470621/INT001SCMS05_ShipReq_ORA_VDIYFR_69646215_20230707055117.txt)

**Comment by DelphinoVarela** [comment]
Hi,

Unfortunately Verisure/Securitas Direct IT isn't very reliable, the provided samples were probably made manually...

Please, change the XSD to allow empty value.
Sorry about that.

**Comment by mm-catdev** [comment]
The XSD will be changed to accept string on this field, as this is the only way to accept null values
