### ISSUE TITLE
VE FR - Mapping Enhancement - ItemNumber and OrderedQuantity

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#22]
**Is your feature request related to a problem? Please describe.**
In Inbound process, map the tags : 
- ItemNumber into the property XA_DIYA_ItemNumber (warning we can have multiple OutboundShipmentLine)
- OrderedQuantity into the property XA_DIYA_OrderedQuantity (warning we can have multiple OutboundShipmentLine)
Those fields will be used in an OFS filter for APAJH to prepare their batches of shipments. 

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
Using a Filter, in OFS, on XA_DIYA_SOURCE_XML, but we have a bug (SR 3-34208197501 : VE FR - sdfrance1.test - 23 C SU 4 - Filter condition "Contains" issue with a large string)
Using a Message Scenario set property but we have a bug (on the property XA_DIYA_SOURCE_XML blocking condition).

**Additional context**
NA

**Comment by mm-catdev** [comment]
Hi Delphino. There are more than one OutboundShipmentLine per activity. How are you planning to map those several different itemNumber in one single itemNumber property ( the same applies for OrderedQuantity )

Options : the first one, separated by comma or SUM ( for the OrderQuantity only )

**Comment by DelphinoVarela** [comment]
The best option : csv

**Comment by be-ant** [comment]
DEV+TEST+Documentation Update: 1 hour

**Comment by be-ant** [comment]
Delivered in release 1.2

**Comment by DelphinoVarela** [comment]
Tests okay
