### ISSUE TITLE
VE FR - st3am-etl-1.2 - Outbound file naming

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#23]
**Affected Plugin / Project**
st3am-etl-1.2

**Describe the bug**
Current xml file name produced are like : YYYYMMDDHHmmss.xml
It was requested to have it with a constant prefix.

**To Reproduce**
NA

**Expected behavior**
xXml file name produced should be like : prefix_YYYYMMDDHHmmss.xml ("prefix" being a variable. With current information the prefix will be set to : "INT001SCMS07_ShipConf_VDIYFR_ORA_")

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Design document changed

**Comment by be-ant** [comment]
Confirmed that customer accepts the timestamp format in YYYMMDDTHHMMSS format

**Comment by DelphinoVarela** [comment]
Tested okay
