### ISSUE TITLE
VE FR - st3am-etl-1.2 - Error running st3am-verisure-inbound/transform_inbound_data

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#24]
**Affected Plugin / Project**
st3am-etl-1.2

**Describe the bug**
The step transform_inbound_data is failing in error (attaching the log)

**To Reproduce**
Use Verisure Test env. (attaching the variable json)
Better to see it online together

**Expected behavior**
No error

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
I changed the XSDs to match new available tags (attaching it).
The XSDs changes were okay with st3am-etl-1.0.2 version

[Archive.zip](https://github.com/ST3AM-US/st3am-com-issues/files/12619151/Archive.zip)

**Comment by mm-catdev** [comment]
Would you mind sharing the input XML that generated this error so I can reproduce it myself ?

**Comment by DelphinoVarela** [comment]
File attached
[INT001SCMS05_ShipReq_ORA_VDIYFR_71402490_20230913161431.xml.zip](https://github.com/ST3AM-US/st3am-com-issues/files/12619735/INT001SCMS05_ShipReq_ORA_VDIYFR_71402490_20230913161431.xml.zip)

**Comment by mm-catdev** [comment]
Error reproduced.

Change request : the tag Price needs to be included in the XSD OutboundShipmentOrder.xsd according to this XML sample

         <OutboundShipmentLine>
            <ShipmentLine>17491775</ShipmentLine>
            <ActionType>CREATE</ActionType>
            <SalesOrderLine>1</SalesOrderLine>
            <ItemNumber>7014</ItemNumber>
            <OrderedQuantity unitCode="Each">1</OrderedQuantity>
            <OrderedQuantityUOMName>Each</OrderedQuantityUOMName>
            <Subinventory>LWFRDYGE</Subinventory>
            <ShippingInstructions/>
            <SourceHeaderNumber>7856851</SourceHeaderNumber>
            <Price/>
         </OutboundShipmentLine>

**Comment by DelphinoVarela** [comment]
Here the new XSD fixing the issue (before I was updating the wrong file)

[OutboundShipmentOrder.xsd.zip](https://github.com/ST3AM-US/st3am-com-issues/files/12621271/OutboundShipmentOrder.xsd.zip)

**Comment by DelphinoVarela** [comment]
Fixed
