### ISSUE TITLE
VE FR - st3am-etl-1.2 - Outbound <Delivery_Name> value

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#25]
**Affected Plugin / Project**
st3am-etl-1.2

**Describe the bug**
Tags <Delivery_Name> value is the current file name including ".xml"
It shouldn't include ".xml"

**To Reproduce**
see attached file

**Expected behavior**
Tags <Delivery_Name> value should:
- not include ".xml"
- not include the prefix of the file name (see https://github.com/ST3AM-US/st3am-com-issues/issues/23)

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

[20230913T142836.xml.zip](https://github.com/ST3AM-US/st3am-com-issues/files/12619214/20230913T142836.xml.zip)

**Comment by be-ant** [comment]
Just to ensure is is 100% clear:

- if filename is 'PREFIX_20230914T0000.xml" then delivery_name will be 20230914T0000

**Comment by DelphinoVarela** [comment]
Confirmed

**Comment by DelphinoVarela** [comment]
Tested okay
