### ISSUE TITLE
VE FR - st3am-etl-1.2 - Enhancement - Outbound add <Subinventory> in each <ShipmentLine>

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#26]
**Is your feature request related to a problem? Please describe.**
It's not matching the structure expected from Verisure Spain IT

**Describe the solution you'd like**
The blocks <ShipmentLine> should include the tag <Subinventory> coming from XA_DIYA_SOURCE_XML

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
I don´t understand this issue.

Could you please explain which section of the Design Document  mentions the Sub-inventory tag ? If we need to include it, please let us know so we can include this enhancement.

NOTE : In the document that you shared with us, the sub-inventory tag is included in the examples, but it is not included neither in any mapping.

**Comment by DelphinoVarela** [comment]
In https://docs.google.com/document/d/1ijzrQoGrt6sBowBnvmpxrH2zAaZrNRt8hrJdBa6JzI4/edit we are talking about : [FC5. Transform Outbound Data](https://docs.google.com/document/d/1ijzrQoGrt6sBowBnvmpxrH2zAaZrNRt8hrJdBa6JzI4/edit#heading=h.d20zopwbn96a)

In my document we are talking about 3.2.	DIYA_FON¬_09 (as it's an "enhancement" of course it wasn't initially documented)

Currently outbound generated XML is : 
```html
<ShipmentConfirmations>
    <ShipmentConfirmation>
        <ActualShipDate>20230913</ActualShipDate>
        <OrganizationCode>LWFRDY</OrganizationCode>
        <Delivery_Name>20230913T142836.xml</Delivery_Name>
        <CarrierName>TNT</CarrierName>
        <ModeOfTransport>TRUCK</ModeOfTransport>
        <ServiceLevel>STANDARD</ServiceLevel>
        <Volume>0.00055647</Volume>
        <VolumeUOMName>Cubic Meter</VolumeUOMName>
        <GrossWeight>0.044</GrossWeight>
        <WeightUOMName>Kilogram</WeightUOMName>
        <Waybill>GPVFR2300000046</Waybill>
        <NumberOfBundles>1</NumberOfBundles>
        <ShipmentLine>
            <Delivery_Name>20230913T142836.xml</Delivery_Name>
            <Shipmentline>17538779</Shipmentline>
            <ItemNumber>7014</ItemNumber>
            <ShippedQuantity>1</ShippedQuantity>
            <Shipped_Quantity_UOM>Each</Shipped_Quantity_UOM>
            <QuantityToBackorder>0</QuantityToBackorder>
        </ShipmentLine>
    </ShipmentConfirmation>
</ShipmentConfirmations>
``` 

Expected : 
```html
<ShipmentConfirmations>
    <ShipmentConfirmation>
        <ActualShipDate>20230913</ActualShipDate>
        <OrganizationCode>LWFRDY</OrganizationCode>
        <Delivery_Name>20230913T142836</Delivery_Name>
        <CarrierName>TNT</CarrierName>
        <ModeOfTransport>TRUCK</ModeOfTransport>
        <ServiceLevel>STANDARD</ServiceLevel>
        <Volume>0.00055647</Volume>
        <VolumeUOMName>Cubic Meter</VolumeUOMName>
        <GrossWeight>0.044</GrossWeight>
        <WeightUOMName>Kilogram</WeightUOMName>
        <Waybill>GPVFR2300000046</Waybill>
        <NumberOfBundles>1</NumberOfBundles>
        <ShipmentLine>
            <Delivery_Name>20230913T142836</Delivery_Name>
            <Shipmentline>17538779</Shipmentline>
            <ItemNumber>7014</ItemNumber>
            <ShippedQuantity>1</ShippedQuantity>
            <Shipped_Quantity_UOM>Each</Shipped_Quantity_UOM>
            <QuantityToBackorder>0</QuantityToBackorder>
            <Subinventory>LWFRDYGE</Subinventory>
        </ShipmentLine>
    </ShipmentConfirmation>
</ShipmentConfirmations>
``` 


You can get the new line  ```html<Subinventory>LWFRDYGE</Subinventory>``` 

from the property XA_DIYA_SOURCE_XML

Technicaly you have to update outbound_map_shipment_line in vsTransformation.py

**Comment by DelphinoVarela** [comment]
The previous message was updated to be readable.

**Comment by DelphinoVarela** [comment]
Tested okay
