### ISSUE TITLE
VE FR - st3am-etl-1.3 - Outbound - <OrganizationCode>

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#29]
**Affected Plugin / Project**
st3am-etl-1.3

**Describe the bug**
Tag OrganizationCode from Outbound XML is set to "NOT SET". 

**To Reproduce**
NA

**Expected behavior**
It is suppose to take the value of the Variable outbound_organization

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
I'm looking into vsTransformation.py and I'm seeing a change in outbound_map_shipment_confirmation : "OrganizationCode": Configuration("organization_code"),
But I'm not seeing it defined in "class Configuration"

**Comment by be-ant** [comment]
Please see the README / Airflow variables

For the Outbound the configuration class is just a proxy to the airflow variables. So if you set an airflow variable called `outbound_organization` then it will map the value correctly

**Comment by DelphinoVarela** [comment]
It was already set (from v1.2), but now it's not taking into account the variable (see screenshot).

![image](https://github.com/ST3AM-US/st3am-com-issues/assets/65107297/91c55c56-59aa-43bd-986c-6be4ae461977)

**Comment by be-ant** [comment]
Confirmed. The error is in the README file, as the variable should be named `organization_code`

**Comment by DelphinoVarela** [comment]
Tested okay
