### ISSUE TITLE
NA PA - Details of a "Formulario"

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#3]
**Affected Plugin**
VAL-FORM

**Describe the bug**
Only photos from Formulario details are displayed not the rest of the properties

**To Reproduce**
1. Search the apptNumber 33101079
2. Open the Details
3. Click on Validate Form button
4. Click on 1042585. TR003. SR308. RE30201. 1042585. 2022-11-01 22:10:24

**Current behavior**
Photos are displayed but not the other properties

**Expected behavior**
All properties of the formSR should be displayed (see page 19 : https://docs.google.com/document/d/19BXTsuXpilYqMpUx3_p64-ICTsWvQr581z56Wgz119I/edit#)

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://drive.google.com/file/d/1I4QDHWE4qn2C663AaXNSKQ9c86Mkw4t0/view?usp=share_link)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by be-ant** [comment]
Several comments:

- There are two orders with that same id. I am assuming we are talking about the non scheduled one (aid: 864861)
- From the fields listed in page 19:
   - Notes: **Work as Designed** The expected field name is `XS_SIT_NOTAS`, but the event contains a field named `XS_NOTE` so it is not presented
   - Description: **Bug Confirmed**. Will add it
   -` XS_SIT_TIPO_REP, XS_SIT_SUBTIPO_REP, XS_SIT_SUBTIPO_REG`": **Duplicated: #2**: Labels are present but values not

![image](https://user-images.githubusercontent.com/91206666/201540361-0ea7d22e-f9dd-4d56-a0c8-683d2595a7c2.png)

**Comment by DelphinoVarela** [comment]
XS_NOTE replaced by XS_SIT_NOTAS : tested okay
