### ISSUE TITLE
NA PA - PA_SIT_REP_ACTUALIZADO_TIPO_REP, PA_SIT_REP_ACTUALIZADO_SUBTIPO_REP, PA_SIT_REP_ACTUALIZADO_SUBTIPO_REG, PA_SIT_REP_ACTUALIZADO_DESCRIPCION

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#5]
**Affected Plugin**
VAL-FORM

**Describe the bug**
Some properties doesn't contain the right value. Other are empty

**To Reproduce**
1. Open the details of an activity with a form to be validated
2. Open VAL-FORM
3. Select a form to be validated
4. Press Rechazar
5. Perform a Get Activity

**Current behavior**
Test performed with ApptNumber 33101079 and Request ID 1042593
In the Get Activity we have :
   "PA_SIT_REP_ACTUALIZADO_TIPO_REP": "Hito",
    "PA_SIT_REP_ACTUALIZADO_SUBTIPO_REP": "Calidad: Equipamiento",
We don't have : PA_SIT_REP_ACTUALIZADO_SUBTIPO_REG and PA_SIT_REP_ACTUALIZADO_DESCRIPCION

**Expected behavior**
PA_SIT_REP_ACTUALIZADO_TIPO_REP and PA_SIT_REP_ACTUALIZADO_SUBTIPO_REP should hold a label not a name
PA_SIT_REP_ACTUALIZADO_SUBTIPO_REG should exist (with a label)
PA_SIT_REP_ACTUALIZADO_DESCRIPCION with the value of the corresponding XS_SIT_DESCRIPCION

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
The consequence is : SIT_ACTU isn't able to update some properties

**Comment by be-ant** [comment]
Something is missing there... those fields are updated when ACTUALIZAR is pressed( I don't see that tin the steps).

This is the update message sent when the button is pressed:

![image](https://user-images.githubusercontent.com/91206666/202586824-9c49de59-df79-4d10-af82-e336ec8ba915.png)

New field values are sent (text instead of labels, working on that),  DESCRIPCION is sent.

**Comment by be-ant** [comment]
Confirmed that SUBTIPO_REG was misspelled as TIPO_REG

**Comment by be-ant** [comment]
Please confirm resolution

**Comment by DelphinoVarela** [comment]
Confirmed
