### ISSUE TITLE
NA PA - El siguiente plugin no se ha cargado: Validate From

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#6]
**Affected Plugin**
VAL-FORM

**Describe the bug**
After the login an error message is displayed "El siguiente plugin no se ha cargado: Validate From"

**To Reproduce**
1. Login as brigada_applusa_10 (pwd : 1234)
2. Wait the green message (Preparando datos para fueran  de linea) on '....'

**Current behavior**
Green message is very long then an error message is displayed: "El siguiente plugin no se ha cargado: Validate From"

**Expected behavior**
Green message should not be displayed more than a couple of seconds and no message error should be displayed

**Screenshots**
See attached file
![image](https://user-images.githubusercontent.com/65107297/205616912-a8e27f0d-dbf7-47a7-be1a-4b7090ea67a4.png)

**Desktop (please complete the following information):**
NA (test performed from a a computer using Chrome v.  107.0.5304.110)

**Smartphone (please complete the following information):**
NA 

**Additional context**
I upgraded to 22C SU 17 (after having identified the issue but the behaviour is the same)

**Comment by mm-catdev** [comment]
Hi team.

Plugin won't work in incognito browser, due to cache usage.

Please try it again without using incognito.

Regards

**Comment by DelphinoVarela** [comment]
Tested okay
