### ISSUE TITLE
NA PA - PA_SIT_REP_ACTUALIZADO_DESCRIPCION not updated

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#7]
**Affected Plugin**
VAL-FORM

**Describe the bug**
PA_SIT_REP_ACTUALIZADO_DESCRIPCION isn't updated by the plugin

**To Reproduce**
You are technician and you have one pending Report in status "waiting for data"
1. Open the Plugin
2. Select the Report in status "waiting for data"
3. Press Actualizar
4. Perform a Get activity

**Current behavior**
PA_SIT_REP_ACTUALIZADO_DESCRIPCION is not available

**Expected behavior**
According https://docs.google.com/document/d/19BXTsuXpilYqMpUx3_p64-ICTsWvQr581z56Wgz119I/edit#  (section Form parameters) PA_SIT_REP_ACTUALIZADO_DESCRIPCION should be available

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Hi Team

We have tried to reproduce the issue, but we have not been able to do it.

Could you please provide us with an example ? 

On the other hand,  the assumption is that the description copied on that PA_SIT_REP_ACTUALIZADO_DESCRIPCION will be from the last form sent, just in case somebody updates that description during the ACTUALIZAR process.

Are you going to copy the PA_SIT_REP_ACTUALIZADO_DESCRIPCION to the property XS_SIT_DESCRIPCION of the form, and sending it, as part of the Update form ?

Regards

**Comment by DelphinoVarela** [comment]
I redid the test and I'm not reproducing it (visibly I was doing something wrong)
