### ISSUE TITLE
NA PA - VAL-FORM Forms History

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#8]
**Affected Plugin**
VAL-FORM

**Describe the bug**
VAL-FORM displays only the latest forms. It's not displaying the parent ones

**To Reproduce**
1. Open the activity Details of the apptNumber 865043
2. Click on SIT form history (VAL-FORM)
3. Perform a Get https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/activities/865085
4. Check XA_SIT_FORM_HISTORICO (it contains 2 SR with the same XS_SIT_GRUPO : 1042616)

**Current behavior**
VAL-FORM displays the latest SR/form (243843 / 1042620)

**Expected behavior**
VAL-FORM should display all SR / forms (Parent SR / form with photos, text, status... and below the children SR / from with photos, text, status...). I'm almost sure I've see it working as expected (see US1.3 User expands one Request
 and US14 User collapses one Request).

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Hi 

We can see both forms

![image](https://user-images.githubusercontent.com/91625466/207122186-70832284-f239-4498-8a48-949f9e7acd28.png)

We have tested all the activities with appt_number 865043, and in all of them we can see the 2 forms.

**Comment by DelphinoVarela** [comment]
Hello,

I don't know how you were able to do you screenshot.
I'm getting
![image](https://user-images.githubusercontent.com/65107297/207610469-ee969223-3b07-4248-9759-48225ed05c8f.png)

**Comment by DelphinoVarela** [comment]
I understood the issue the symbol at the beginning of the 1st row isn't extremely visible (in consequence you don't know you can click on it). Can it be enhanced, please ?

Now what I'm seeing : 
  1- In XA_SIT_FORM_HISTORICO we have "eventType": "formSubmitted", "time": "2022-12-14 14:37:40",
  2- The screenshot isn't showing it (apptNumber : 865043)
![image](https://user-images.githubusercontent.com/65107297/207639290-259ff473-7d1f-4168-85b0-69f274c1f3bb.png)

**Comment by DelphinoVarela** [comment]
I thought I messed up with PA_SIT_FORM_DATOS_0. In consequence I redid a full test cycle and I'm reproducing the same behaviour (I did a SIT_ACTU of the form "Rechazado", but the SIT_ACTU isn't accessible). 

![image](https://user-images.githubusercontent.com/65107297/207932751-1db81ed6-7650-44f7-8cb0-118df96ee425.png)

XA_SIT_FORM_HISTORICO
[
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:18:52",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042643",
                "formLabel": "SIT_CREA"
            },
            "requestDetails": {
                "requestId": 243866,
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_NOTAS": "Problema 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042643/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:40:42",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042644",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243867,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta a Descripcion 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042644/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:46:29",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042645",
                "formLabel": "SIT_CREA"
            },
            "requestDetails": {
                "requestId": 243868,
                "XS_SIT_TIPO_REP": "TR001",
                "XS_SIT_SUBTIPO_REP": "SR303",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_NOTAS": "Nota 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (6).jpg, 148KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042645/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_DOC2": {
                    "filename": "capture_image (5).jpg, 76KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042645/requestFiles/XS_SIT_DOC2"
                },
                "XS_SIT_VALIDACION_REQ": 0,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:51:00",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042646",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243869,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta al rechazo con razon 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (3).jpg, 113KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042646/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        }
]

**Comment by be-ant** [comment]
Can you please share the console log? It will help us to figure out quickly the reason the last one was not added. You should find there a set of messages like:  getRequests: ... Skipped form, ...... Adding child

**Comment by mm-catdev** [comment]
Hi.
With the appt_number that you are mentioning,  I can see several different activities


![image](https://user-images.githubusercontent.com/91625466/208476541-f75ae0fc-73c5-46fe-9f4b-f3dd30051ba9.png)


I have loaded some of them , and I have not been able to find the scenario you are mentioning. Could you please use an unique appt_number for the testing ? That will make easier to reproduce it when you are reporting it.

**Comment by mm-catdev** [comment]
Hi team.

I have deleted all the information in the PA_SIT_FORM_DATOS and I have copied the content that you have included in this SR, and I have been able to see the information correctly.

![image](https://user-images.githubusercontent.com/91625466/208478584-c9fcb7fa-bcc5-4a1e-b3f5-22d7646da44f.png)


I don't know how to reproduce the issue.

**Comment by DelphinoVarela** [comment]
Please check : apptNumber 865204 (non-schedule or the one for today - I will change later the configuration to not use any more "Enable segmenting", it will match better this project phase).

The behaviour I'm suspecting : after a "Rechazado", all forms/request, from the same group, performed after are not visible.
You can try to reproduce (I reproduced it twice).

**Comment by mm-catdev** [comment]
Hi team,

I can see it without any problem

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/91625466/208558754-36b21c0b-271a-477b-939f-a5dfa4424455.png">



Which is the form that we should see and you are not able to see ? could you please include the screenshot ? Any specific form that I need to reject to reproduce the issue ?

**Comment by DelphinoVarela** [comment]
Please Miguel let's have a meeting

**Comment by mm-catdev** [comment]
Use this appointment

<img width="914" alt="image" src="https://user-images.githubusercontent.com/91625466/208938024-f3b3bfa0-c255-4793-bb1c-31db75e57eb6.png">

**Comment by mm-catdev** [comment]
This is the section that is not showing properly

_[
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:18:52",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042643",
                "formLabel": "SIT_CREA"
            },
            "requestDetails": {
                "requestId": 243866,
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_NOTAS": "Problema 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042643/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:40:42",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042644",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243867,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta a Descripcion 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042644/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:51:00",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042646",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243869,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta al rechazo con razon 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (3).jpg, 113KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042646/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        }
]_

**Comment by mm-catdev** [comment]
Original information when the issue is happening

HISTORICO

[
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:18:52",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042643",
                "formLabel": "SIT_CREA"
            },
            "requestDetails": {
                "requestId": 243866,
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_NOTAS": "Problema 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042643/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:40:42",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042644",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243867,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta a Descripcion 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (4).jpg, 66KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042644/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:46:29",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042645",
                "formLabel": "SIT_CREA"
            },
            "requestDetails": {
                "requestId": 243868,
                "XS_SIT_TIPO_REP": "TR001",
                "XS_SIT_SUBTIPO_REP": "SR303",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_NOTAS": "Nota 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (6).jpg, 148KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042645/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_DOC2": {
                    "filename": "capture_image (5).jpg, 76KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042645/requestFiles/XS_SIT_DOC2"
                },
                "XS_SIT_VALIDACION_REQ": 0,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 17:51:00",
            "user": "brigada_applusa_10",
            "formIdentifier": {
                "formSubmitId": "1042646",
                "formLabel": "SIT_ACTU"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_ACTUALIZACION_REQUERIDA": 0,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243869,
                "XS_SIT_TIPO_REP": "TR003",
                "XS_SIT_SUBTIPO_REP": "SR311",
                "XS_SIT_SUBTIPO_REG": "RE30201",
                "XS_SIT_DESCRIPCION": "Descripcion 1",
                "XS_SIT_NOTAS": "Respuesta al rechazo con razon 1",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (3).jpg, 113KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042646/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_ESTADO": "00",
                "XS_SIT_VALIDACION_REQ": 1,
                "XS_SIT_GRUPO": "1042643",
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 18:11:06",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042647",
                "formLabel": "SIT_CREA"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243870,
                "XS_SIT_TIPO_REP": "TR002",
                "XS_SIT_SUBTIPO_REP": "SR309",
                "XS_SIT_NOTAS": "Test 3",
                "XS_SIT_DOC1": {
                    "filename": "Screenshot_20220309-164229_Field Service.jpg, 197KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042647/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_VALIDACION_REQ": 0,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 19:23:38",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042648",
                "formLabel": "SIT_CREA"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243871,
                "XS_SIT_TIPO_REP": "TR004",
                "XS_SIT_SUBTIPO_REP": "SR102",
                "XS_SIT_SUBTIPO_REG": "RE30103",
                "XS_SIT_NOTAS": "Test 4",
                "XS_SIT_DOC1": {
                    "filename": "capture_image (6).jpg, 148KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042648/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_VALIDACION_REQ": 0,
                "requestType": "SIT"
            }
        },
        {
            "eventType": "formSubmitted",
            "time": "2022-12-15 19:33:57",
            "user": "delphino.varela",
            "formIdentifier": {
                "formSubmitId": "1042649",
                "formLabel": "SIT_CREA"
            },
            "activityDetails": {
                "activityId": 865204,
                "PA_SIT_PUEDE_COMPLETAR": 0
            },
            "requestDetails": {
                "requestId": 243872,
                "XS_SIT_TIPO_REP": "TR001",
                "XS_SIT_SUBTIPO_REP": "SR401",
                "XS_SIT_SUBTIPO_REG": "RE31103",
                "XS_SIT_NOTAS": "Test 5",
                "XS_SIT_DOC1": {
                    "filename": "Screenshot_20220309-164229_Field Service.jpg, 197KB",
                    "href": "https://naturgy-pa-des.test.etadirect.com/rest/ofscCore/v1/forms/1042649/requestFiles/XS_SIT_DOC1"
                },
                "XS_SIT_VALIDACION_REQ": 0,
                "requestType": "SIT"
            }
        }
]


PA_SIT_FORM_DATOS_0

{"1042644":{"id":"1042644","date":"2022-12-15 17:40:42","report_type":"TR003","report_subtype":"SR311","register_subtype":"RE30201","description":"Descripcion 1","notes":"Respuesta a Descripcion 1","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"}],"status":2,"_children":[{"id":"1042643","date":"2022-12-15 17:18:52","report_type":"TR003","report_subtype":"SR311","register_subtype":"RE30201","description":"Descripcion 1","notes":"Problema 1","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"}],"status":100,"group_id":"1042643"}],"group_id":"1042643","reason":"Razon 1"},"1042645":{"id":"1042645","date":"2022-12-15 17:46:29","report_type":"TR001","report_subtype":"SR303","register_subtype":"RE30201","description":"","notes":"Nota 1","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"},{"fileType":"jpg","property":"XS_SIT_DOC2"}],"status":10,"group_id":"1042645"},"1042647":{"id":"1042647","date":"2022-12-15 18:11:06","report_type":"TR002","report_subtype":"SR309","description":"","notes":"Test 3","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"}],"status":10,"group_id":"1042647"},"1042648":{"id":"1042648","date":"2022-12-15 19:23:38","report_type":"TR004","report_subtype":"SR102","register_subtype":"RE30103","description":"","notes":"Test 4","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"}],"status":10,"group_id":"1042648"},"1042649":{"id":"1042649","date":"2022-12-15 19:33:57","report_type":"TR001","report_subtype":"SR401","register_subtype":"RE31103","description":"","notes":"Test 5","images":[{"fileType":"jpg","property":"XS_SIT_DOC1"}],"status":10,"group_id":"1042649"}}

**Comment by mm-catdev** [comment]
Improvement delivered in Release 1.0.5

**Comment by DelphinoVarela** [comment]
Tested okay
