### ISSUE TITLE
NA PA - XS_SIT_SUBTIPO_REG not displayed in 100% of the cases

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#9]
**Affected Plugin**
VAL-FORM

**Describe the bug**
Sometimes XS_SIT_SUBTIPO_REG isn't displayed in the main VAL-FORM screen (Listado de Formularios)

**To Reproduce**
1. Open apptNumber 865204
2. Check XA_SIT_FORM_HISTORICO ("formSubmitId": "1042649" )
3. Check PA_SIT_FORM_DATOS_0 ("id":"1042649")
4. Open VAL-FORM

**Current behavior**
For "formSubmitId": "1042649"  :
- XA_SIT_FORM_HISTORICO holds "XS_SIT_SUBTIPO_REG": "RE31103",
- PA_SIT_FORM_DATOS_0 holds "register_subtype":"RE31103"
- VAL-FORM doesn't display the column Registro

**Expected behavior**
For "formSubmitId": "1042649"  :
- XA_SIT_FORM_HISTORICO holds "XS_SIT_SUBTIPO_REG": "RE31103",
- PA_SIT_FORM_DATOS_0 holds "register_subtype":"RE31103"
- VAL-FORM should display the column Registro if XS_SIT_SUBTIPO_REG isn't null

**Screenshots**
![image](https://user-images.githubusercontent.com/65107297/207953680-97a483c7-38a7-41e9-983d-f5749117b974.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
I have been able to reproduce de issue.

**Comment by DelphinoVarela** [comment]
Tested okay
